export const AGREGAR_PRODUCTO       = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';


//Carga de productos
export const PRODUCTOS_CARGA    = 'PRODUCTOS_CARGA';
export const PRODUCTOS_CARGADOS = 'PRODUCTOS_CARGADOS';
export const PRODUCTOS_ERROR    = 'PRODUCTOS_ERROR';

//eliminar un producto
export const PRODUCTO_ELIMINAR       = 'PRODUCTO_ELIMINAR';
export const PRODUCTO_ELIMINADO      = 'PRODUCTO_ELIMINADO';
export const PRODUCTO_ELIMINAR_ERROR = 'PRODUCTO_ELIMINAR_ERROR';

//editar producto
export const PRODUCTO_EDITAR       = 'PRODUCTO_EDITAR';
export const PRODUCTO_EDITAR_STATE = 'PRODUCTO_EDITAR_STATE';
export const PRODUCTO_EDITADO      = 'PRODUCTO_EDITADO';
export const PRODUCTO_EDITAR_ERROR = 'PRODUCTO_EDITAR_ERROR';